# Generated by Django 5.0.6 on 2024-07-03 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_usuario_correo_usuario_sugerencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sugerencia',
        ),
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)]),
            preserve_default=False,
        ),
    ]
