# Generated by Django 5.0.6 on 2024-07-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_remove_usuario_sugerencia_usuario_edad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
