# Generated by Django 5.0.6 on 2024-07-03 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
            ],
        ),
    ]
