# Generated by Django 5.0.6 on 2024-07-05 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=50)),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('fecha', models.DateField()),
            ],
        ),
    ]
