# Generated by Django 5.0.6 on 2024-07-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_rename_users_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='email',
        ),
    ]
