# Generated by Django 5.0.6 on 2024-07-03 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_rename_mail_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Comment',
        ),
    ]
