# Generated by Django 5.0.6 on 2024-07-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_rename_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='surname',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='age',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='nombre',
        ),
    ]
