# Generated by Django 5.0.6 on 2024-07-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_rename_surname_comment_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='correo',
        ),
        migrations.AddField(
            model_name='comment',
            name='comentario',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
